### ISSUE TITLE
ui-super-heroes application failing "Crash-loop-back-off"

### ISSUE THREAD

**Issue by nageshredhat** [redhat-gpte-devopsautomation/quarkus-super-heroes-rhbq213#1]
Hi @juliaaano,
I'm using your application in openshift cluster. But node pod is failing and  getting following errors:
```
> super-heroes@0.0.0 start
> node serving/server.js
[2023-06-21T17:53:55.142Z] express server listening on 8080
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /opt/app-root/src/.npm/_cacache/tmp/0d1d142a
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR! sudo chown -R 1000710000:0 "/opt/app-root/src/.npm"
npm ERR! Log files were not written due to an error writing to the directory: /opt/app-root/src/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

Can you please know the solution or can you pls fix from your end.  It seems like permission issue in pod

![image](https://github.com/redhat-gpte-devopsautomation/quarkus-super-heroes-rhbq213/assets/111345802/f243c20c-9896-4836-b619-16ee27d81e6d)

**Comment by juliaaano** [comment]
@nageshredhat can I ask you to try deploying this through the demo platform here: https://demo.redhat.com/catalog?item=babylon-catalog-prod/enterprise.ocp4-acc-new-app-dev.prod

If not, an alternative is to go to the upstream project here: https://github.com/quarkusio/quarkus-super-heroes

I know about this issue, but unfortunately, I haven't been able to determine and fix the root cause. It comes and goes after a while.

Let me know how it goes.

**Comment by nageshredhat** [comment]
Yes i'm deploying through RHPDS (sales play) only

**Comment by nageshredhat** [comment]
still pending

**Comment by juliaaano** [comment]
It should be fixed now, so please try again. @nageshredhat
